
image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-browser
      visibility: public
    - port: 3001
      onOpen: open-preview
      visibility: public
    - port: 5432
      onOpen: ignore
tasks:
    - init: >
        (cp -n .env.example .env || true) && 
        echo "" >> .env && echo "BACKEND_URL=https://3001-${GITPOD_WORKSPACE_URL:8}" >> .env && 
        pipenv install &&
        pipenv run start;
